apiVersion: v1
kind: Secret
metadata:
  name: learnify-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "YOUR_MYSQL_CONNECTION_STRING"
  Jwt__Key: "YOUR_JWT_KEY"
  Google__ClientId: "YOUR_GOOGLE_CLIENT_ID"
  Google__ClientSecret: "YOUR_GOOGLE_CLIENT_SECRET"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: learnify-gateway
spec:
  to:
    kind: Service
    name: gateway-service
  port:
    targetPort: 8080
  tls:
    termination: edge
